# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Life in Boston
email: minminjfu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am currently a PhD student at Harvard University.  This blog is a place for me to upload photos, thoughts, news, and update my friends on what I'm up to lately.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://minminfu.github.io" # the base hostname & protocol for your site
twitter_username: minminfu
github_username:  minminfu
excerpt_separator: <!--more-->
# Build settings
markdown: kramdown
